//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverlightDemoWebService.BlogService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://tempuri.org/")]
    public partial class Post : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int IdField;
        
        private string TitleField;
        
        private string AuthorField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.ServiceModel.ServiceContractAttribute()]
    public interface BlogServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetPosts", ReplyAction="*")]
        System.IAsyncResult BeginGetPosts(SilverlightDemoWebService.BlogService.GetPostsRequest request, System.AsyncCallback callback, object asyncState);
        
        SilverlightDemoWebService.BlogService.GetPostsResponse EndGetPosts(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPosts", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightDemoWebService.BlogService.GetPostsRequestBody Body;
        
        public GetPostsRequest() {
        }
        
        public GetPostsRequest(SilverlightDemoWebService.BlogService.GetPostsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPostsRequestBody {
        
        public GetPostsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPostsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPostsResponse", Namespace="http://tempuri.org/", Order=0)]
        public SilverlightDemoWebService.BlogService.GetPostsResponseBody Body;
        
        public GetPostsResponse() {
        }
        
        public GetPostsResponse(SilverlightDemoWebService.BlogService.GetPostsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPostsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SilverlightDemoWebService.BlogService.Post[] GetPostsResult;
        
        public GetPostsResponseBody() {
        }
        
        public GetPostsResponseBody(SilverlightDemoWebService.BlogService.Post[] GetPostsResult) {
            this.GetPostsResult = GetPostsResult;
        }
    }
    
    public interface BlogServiceSoapChannel : SilverlightDemoWebService.BlogService.BlogServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class GetPostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetPostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public SilverlightDemoWebService.BlogService.Post[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((SilverlightDemoWebService.BlogService.Post[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    public partial class BlogServiceSoapClient : System.ServiceModel.ClientBase<SilverlightDemoWebService.BlogService.BlogServiceSoap>, SilverlightDemoWebService.BlogService.BlogServiceSoap {
        
        private BeginOperationDelegate onBeginGetPostsDelegate;
        
        private EndOperationDelegate onEndGetPostsDelegate;
        
        private System.Threading.SendOrPostCallback onGetPostsCompletedDelegate;
        
        private static System.ServiceModel.Channels.Binding defaultBinding = new System.ServiceModel.BasicHttpBinding();
        
        private static System.ServiceModel.EndpointAddress defaultAddress = new System.ServiceModel.EndpointAddress("http://localhost:1983/BlogService.asmx");
        
        public BlogServiceSoapClient() : 
                this(defaultBinding, defaultAddress) {
        }
        
        public BlogServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetPostsCompletedEventArgs> GetPostsCompleted;
        
        System.IAsyncResult SilverlightDemoWebService.BlogService.BlogServiceSoap.BeginGetPosts(SilverlightDemoWebService.BlogService.GetPostsRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetPosts(request, callback, asyncState);
        }
        
        private System.IAsyncResult BeginGetPosts(System.AsyncCallback callback, object asyncState) {
            SilverlightDemoWebService.BlogService.GetPostsRequest inValue = new SilverlightDemoWebService.BlogService.GetPostsRequest();
            inValue.Body = new SilverlightDemoWebService.BlogService.GetPostsRequestBody();
            return ((SilverlightDemoWebService.BlogService.BlogServiceSoap)(this)).BeginGetPosts(inValue, callback, asyncState);
        }
        
        SilverlightDemoWebService.BlogService.GetPostsResponse SilverlightDemoWebService.BlogService.BlogServiceSoap.EndGetPosts(System.IAsyncResult result) {
            return base.Channel.EndGetPosts(result);
        }
        
        private SilverlightDemoWebService.BlogService.Post[] EndGetPosts(System.IAsyncResult result) {
            SilverlightDemoWebService.BlogService.GetPostsResponse retVal = ((SilverlightDemoWebService.BlogService.BlogServiceSoap)(this)).EndGetPosts(result);
            return retVal.Body.GetPostsResult;
        }
        
        private System.IAsyncResult OnBeginGetPosts(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return this.BeginGetPosts(callback, asyncState);
        }
        
        private object[] OnEndGetPosts(System.IAsyncResult result) {
            SilverlightDemoWebService.BlogService.Post[] retVal = this.EndGetPosts(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetPostsCompleted(object state) {
            if ((this.GetPostsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetPostsCompleted(this, new GetPostsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetPostsAsync() {
            this.GetPostsAsync(null);
        }
        
        public void GetPostsAsync(object userState) {
            if ((this.onBeginGetPostsDelegate == null)) {
                this.onBeginGetPostsDelegate = new BeginOperationDelegate(this.OnBeginGetPosts);
            }
            if ((this.onEndGetPostsDelegate == null)) {
                this.onEndGetPostsDelegate = new EndOperationDelegate(this.OnEndGetPosts);
            }
            if ((this.onGetPostsCompletedDelegate == null)) {
                this.onGetPostsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetPostsCompleted);
            }
            base.InvokeAsync(this.onBeginGetPostsDelegate, null, this.onEndGetPostsDelegate, this.onGetPostsCompletedDelegate, userState);
        }
        
        protected override SilverlightDemoWebService.BlogService.BlogServiceSoap CreateChannel() {
            return new BlogServiceSoapClientChannel(this);
        }
        
        private class BlogServiceSoapClientChannel : ChannelBase<SilverlightDemoWebService.BlogService.BlogServiceSoap>, SilverlightDemoWebService.BlogService.BlogServiceSoap {
            
            public BlogServiceSoapClientChannel(System.ServiceModel.ClientBase<SilverlightDemoWebService.BlogService.BlogServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetPosts(SilverlightDemoWebService.BlogService.GetPostsRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetPosts", _args, callback, asyncState);
                return _result;
            }
            
            public SilverlightDemoWebService.BlogService.GetPostsResponse EndGetPosts(System.IAsyncResult result) {
                object[] _args = new object[0];
                SilverlightDemoWebService.BlogService.GetPostsResponse _result = ((SilverlightDemoWebService.BlogService.GetPostsResponse)(base.EndInvoke("GetPosts", _args, result)));
                return _result;
            }
        }
    }
}
